name: Terraform AWS Workflow Advanced

on:
  workflow_dispatch:


jobs:
  tf_code_check:
    name: Terraform Validation and Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    

    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2 
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        continue-on-error: true
        
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        
